language: python

python:
- "3.10.8"

services:
  - docker
install:
  - pip install -r requirements.txt

script:
  - pipenv run python manage.py test

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: $HEROKU_APP_NAME
  on:
    branch: main

# Path: .travis.yml