language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

services:
  - docker
install:
  - pip install django

env:
  - DOCKER_COMPOSE_VERSION=1.25.0

script:
  - python3 manage.py test

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: $HEROKU_APP_NAME
  on:
    branch: main

# Path: .travis.yml